import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const Color darkBackground = Color(0xFF11110F);
  static const Color splashBackground = Color(0xFF11110F);
  static const Color darkSurface = Color(0xFF1C1C1A);
  static const Color darkCard = Color(0xFF1E1E1C);
  static const Color darkBorder = Color(0xFF2E2E2A);
  static const Color goldFont = Color(0xFFD9A24F);
  static const Color goldGradientStart = Color(0xFFE5B563);
  static const Color goldGradientEnd = Color(0xFFC78B38);
  static const Color cardGoldAccent = Color(0xFFE5A64E);
  static const Color creamText = Color(0xFFFFF1D2);
  static const Color primary = Color(0xFFD9A24F);
  static const Color primaryDark = Color(0xFFB58338);
  static const Color primaryLight = Color(0xFF2E2A20);
  static const Color accentYellow = Color(0xFFFFB800);
  static const Color background = Color(0xFF11110F);
  static const Color surface = Color(0xFF1C1C1A);
  static const Color surfaceVariant = Color(0xFF252522);
  static const Color textPrimary = Color(0xFFFFFFFF);
  static const Color textSecondary = Color(0xFFB3B3B0);
  static const Color textMuted = Color(0xFF7A7A77);
  static const Color textLight = Color(0xFFFFFFFF);
  static const Color textGold = Color(0xFFD9A24F);
  static const Color textPrimaryDark = Color(0xFFFFFFFF);
  static const Color textSecondaryDark = Color(0xFFB3B3B0);
  static const Color textMutedDark = Color(0xFF7A7A77);
  static const Color success = Color(0xFF388E3C);
  static const Color successLight = Color(0xFF1E3A20);
  static const Color warning = Color(0xFFED6C02);
  static const Color warningLight = Color(0xFF3D2B10);
  static const Color error = Color(0xFFE53935);
  static const Color errorLight = Color(0xFF3E1A1A);
  static const Color border = Color(0xFF2E2E2A);
  static const Color borderDark = Color(0xFF3A3A35);
  static const Color divider = Color(0xFF262623);
  static const Color shadow = Color(0x40000000);
  static const Color overlay = Color(0x99000000);
  static const Color veg = Color(0xFF388E3C);
  static const Color nonVeg = Color(0xFFE53935);
}
